#+BEGIN_COMMENT
.. title: Test
.. slug: test
.. date: 2016-09-17 14:24:26 UTC
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT


Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. 



Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. Write your post here. 

#+begin_src python
import sys
import os

if os.path.isdir('/etc'):
    print("/etc/ is a directory.")
    sys.exit(0)
#+end_src

Write your post here. Write your post here.
